name: mobile_lingkunganku
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  chewie: ^1.10.0
  cupertino_icons: ^1.0.8
  detectable_text_field: ^3.0.2
  equatable: ^2.0.7
  file_picker: ^8.1.7
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_contacts: ^1.1.9+2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_mentions: ^2.0.1
  flutter_otp_text_field: ^1.4.0+2
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  get_time_ago: ^2.2.0
  go_router: ^14.6.3
  go_router_builder: ^2.7.3
  google_maps_flutter: ^2.10.0
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  multi_image_picker_plus: ^0.0.6
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^2.2.3
  pod_player: ^0.2.2
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  sn_progress_dialog: ^1.2.0
  table_calendar: ^3.2.0
  timeago: ^3.2.2
  url_launcher: ^6.3.1
  video_compress_v2: ^1.0.0+1
  visibility_detector: ^0.4.0+2
  open_file_plus: ^3.4.1+1
  slide_to_confirm: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.9.3
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icons.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icons.png"
    background_color: "#236C06"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/icons.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icons.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
